config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  resources :users, except: [:new]

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    # only validate password length on create (not update)
    validates :password, length: { minimum: 6 }, on: :create
  
    validates :email,
        presence: true,
        uniqueness: true,
        format: {
            with: /@/,
            message: "not a valid format"
        }
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
      def new
        # don't let current_user see the log in view
        if current_user
          redirect_to user_path(current_user)
        end
      end
    
      def create
        @user = User.find_by_email(user_params[:email])
        # If the user exists AND the password entered is correct.
        if @user && @user.authenticate(user_params[:password])
          # Save the user id inside the browser cookie. This is how we keep the user 
          # logged in when they navigate around our website.
          session[:user_id] = @user.id
          flash[:notice] = "Successfully logged in."
          redirect_to user_path(@user)
        else
          flash[:error] = "Incorrect email or password."
          redirect_to login_path
        end
      end
    
      def destroy
        session[:user_id] = nil
        flash[:notice] = "Successfully logged out."
        redirect_to root_path
      end
    
      private
    
        def user_params
          params.require(:user).permit(:email, :password)
        end
    
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, except: [:index, :new, :create]
    # before_action :authorize, only: [:edit, :update, :destroy]

    def index
      @users = User.all
    end

    def new
      # don't let current_user see the sign up view
      if current_user
        redirect_to user_path(current_user)
      else
        @user = User.new
      end
    end

    def create
      # don't let current_user create new account
      if current_user
        redirect_to user_path(current_user)
      else
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:notice] = "Successfully signed up."
          redirect_to user_path(@user)
        else
          flash[:error] = @user.errors.full_messages.join(", ")
          redirect_to signup_path
        end
      end
    end

    def show
    end

    def edit
      # don't let current_user see another user's edit view
      if current_user != @user
        redirect_to user_path(current_user)
      end
    end

    def update
      # only let current_user update their own account
      if current_user == @user
        if @user.update_attributes(user_params)
          flash[:notice] = "Successfully updated profile."
          redirect_to user_path(@user)
        else
          flash[:error] = @user.errors.full_messages.join(", ")
          redirect_to edit_user_path(@user)
        end
      else
        redirect_to user_path(current_user)
      end
    end

    def destroy
      # only let current_user delete their own account
      if current_user == @user
        @user.destroy
        session[:user_id] = nil
        flash[:notice] = "Successfully deleted profile."
        redirect_to root_path
      else
        redirect_to user_path(current_user)
      end
    end

    private

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end

      def set_user
        user_id = params[:id]
        @user = User.find_by_id(user_id)
      end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- bootstrap css -->
  <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- application stylesheet -->
  <%= stylesheet_link_tag :application, media: :all %>

  <title>RailsBlogApp</title>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "RailsBlogApp", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "All Users", users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% flash.each do |name, msg| %>
    <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
      <div class="container">
        <%= msg %>
      </div>
    </div>
  <% end %>
  <div class="container site-content">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>
  
  <!-- application javascript file -->
  <%= javascript_include_tag :application %>

  <!-- bootstrap js -->
  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<hr>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "email@example.com", class: "form-control", autofocus: true %>
  </div>
  <%= f.submit "Save Profile", class: "btn btn-block btn-default" %>
<% end %>

app/views/users/index.html.erb
<h1>Welcome to the blog!</h1>
<hr>
<% @users.each do |user| %>
  <%= user.email %> - <%= link_to "View Profile", user_path(user) %>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<hr>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "email@example.com", class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Must be at least 6 characters", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-block btn-default" %>
<% end %>
<br>
<p>Already have an account? <%= link_to "Click here", login_path %> to log in.</p>

app/views/users/show.html.erb
<h1>User Profile</h1>
<hr>
<p><strong>Email:</strong> <%= @user.email %></p>
<p class="small text-muted">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>

<!-- only let user who owns this account see edit/delete buttons -->
<% if current_user && current_user == @user %>
  <hr>
  <p>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-default" %>
    <%= link_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-default" %>
  </p>
<% end %>